#!/bin/bash
#php vendor/bin/codecept generate:test unit PlayerCredit -c common # make new test
#php vendor/bin/codecept run common/tests/unit/PlayerCreditTest.php --fail-fast # run fewer tests
php vendor/bin/codecept run # run all tests (slow)
