<?php
return [
    'adminEmail' => 'no-reply@westmarchesgame.com',
    'supportEmail' => 'no-reply@westmarchesgame.com',
    'senderEmail' => 'no-reply@westmarchesgame.com',
    'senderName' => 'No Reply',
    'user.passwordResetTokenExpire' => 3600,
    'user.passwordMinLength' => 8,
    'navigation' => [
        'isAdmin' => [
            'announcements' => '/frontend/web/campaign-announcement',
            'documents' => '/frontend/web/campaign-document',
            'games' => '/frontend/web/game',
            'maps' => '/frontend/web/map',
            'players' => '/frontend/web/campaign-player',
            'characters' => '/frontend/web/campaign-character',
            'equipments' => '/frontend/web/equipment',
            'purchases' => '/frontend/web/purchase',
            'currencies' => '/frontend/web/currency',
            'complaints' => '/frontend/web/player-complaint',
            'triggers' => '/frontend/web/player-trigger',
            'tickets' => '/frontend/web/ticket',
            'forms' => '/frontend/web/form',
            'rules' => '/frontend/web/campaign/view',
        ],
        'isHost' => [
            'announcements' => '/frontend/web/campaign-announcement',
            'documents' => '/frontend/web/campaign-document',
            'games' => '/frontend/web/game',
            'maps' => '/frontend/web/map',
            'players' => '/frontend/web/campaign-player',
            'characters' => '/frontend/web/campaign-character',
            'equipments' => '/frontend/web/equipment',
            'purchases' => '/frontend/web/purchase',
            'currencies' => '/frontend/web/currency',
            'complaints' => '/frontend/web/player-complaint',
            'triggers' => '/frontend/web/player-trigger',
            'tickets' => '/frontend/web/ticket',
            'forms' => '/frontend/web/form',
            'rules' => '/frontend/web/campaign/view',
        ],
        'isPlayer' => [
            'announcements' => '/frontend/web/campaign-announcement',
            'documents' => '/frontend/web/campaign-document',
        ],
    ]
];
